import { Column } from '@/components/table/DataTableWithColumnSearch';
import { Eye, Trash2, Download } from 'lucide-react';

export interface Report {
  report_id: number;
  name: string;
  type: string;
  generated_by: string;
  date: string;
  total_records: number;
  format: string;
  generated_at: string;
  status: 'Completed' | 'Processing' | 'Failed';
}

export const reportColumns = (
  handleView: (row: Report) => void,
  handleDelete: (row: Report) => void,
  handleDownload: (row: Report) => void
): Column<Report>[] => [
  {
    key: 'report_id',
    label: 'REPORT ID',
    position: 'middle',
    sortable: true,
    sortFn: (a, b) => a.report_id - b.report_id,
  },

  {
    key: 'name',
    label: 'REPORT NAME',
    position: 'middle',
    sortable: true,
    sortFn: (a, b) =>
      (a.name ?? '').localeCompare(b.name ?? ''),
  },

  {
    key: 'type',
    label: 'TYPE',
    position: 'middle',
    sortable: true,
    sortFn: (a, b) =>
      (a.type ?? '').localeCompare(b.type ?? ''),
  },

  {
    key: 'generated_by',
    label: 'GENERATED BY',
    position: 'middle',
    sortable: true,
    sortFn: (a, b) =>
      (a.generated_by ?? '').localeCompare(b.generated_by ?? ''),
  },

  {
    key: 'date',
    label: 'DATE',
    position: 'middle',
    sortable: true,
    sortFn: (a, b) =>
      new Date(a.date).getTime() - new Date(b.date).getTime(),

    render: (row: Report) => {
      const raw = row?.date;
      if (!raw) return '';

      const d = new Date(raw);
      if (isNaN(d.getTime())) return String(raw);

      const dd = String(d.getDate()).padStart(2, '0');
      const mm = String(d.getMonth() + 1).padStart(2, '0');
      const yyyy = d.getFullYear();

      return `${yyyy}-${mm}-${dd}`;
    },
  },

  {
    key: 'total_records',
    label: 'TOTAL RECORDS',
    position: 'middle',
    sortable: true,
    sortFn: (a, b) => a.total_records - b.total_records,
  },

  {
    key: 'format',
    label: 'FORMAT',
    position: 'middle',
    sortable: true,
    sortFn: (a, b) =>
      (a.format ?? '').localeCompare(b.format ?? ''),
  },

  {
    key: 'generated_at',
    label: 'GENERATED AT',
    position: 'middle',
    sortable: true,
    sortFn: (a, b) =>
      new Date(a.generated_at).getTime() -
      new Date(b.generated_at).getTime(),
  },

  {
    key: 'status',
    label: 'STATUS',
    position: 'middle',
    sortable: true,

    sortFn: (a, b) => {
      const order = {
        Completed: 1,
        Processing: 2,
        Failed: 3,
      };

      return order[a.status] - order[b.status];
    },

    render: (row) => {
      const statusStyle: Record<Report['status'], string> = {
        Completed: 'bg-green-100 text-green-700 border-green-200',
        Processing: 'bg-yellow-100 text-yellow-700 border-yellow-200 animate-pulse',
        Failed: 'bg-red-100 text-red-700 border-red-200',
      };

      return (
        <span
          className={`px-3 py-1 rounded-full text-xs font-semibold border ${statusStyle[row.status]}`}
        >
          {row.status}
        </span>
      );
    },
  },

  {
    key: 'action',
    label: 'ACTION',
    position: 'middle',
    sortable: false,

    actions: [
      {
        icon: Eye,
        variant: 'outline',
        tooltip: 'View Report',
        onClick: (row) => handleView(row),
      },
      {
        icon: Download,
        variant: 'success',
        tooltip: 'Download Report',
        onClick: (row) => handleDownload(row),
      },
      {
        icon: Trash2,
        variant: 'danger',
        tooltip: 'Delete Report',
        onClick: (row) => handleDelete(row),
      },
    ],
  },
];