--
-- PostgreSQL database dump
--

\restrict rDAbeUtflX5w1Pbim9eXy0xYjbJ28oLzKvAbjbYn4VR9f8eXprPb45xwcfW1mNj

-- Dumped from database version 18.3
-- Dumped by pg_dump version 18.3

-- Started on 2026-03-10 11:47:42

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 7 (class 2615 OID 17988)
-- Name: reach10_mysql; Type: SCHEMA; Schema: -; Owner: postgres
--

CREATE SCHEMA reach10_mysql;


ALTER SCHEMA reach10_mysql OWNER TO postgres;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 284 (class 1259 OID 17989)
-- Name: contract; Type: TABLE; Schema: reach10_mysql; Owner: postgres
--

CREATE TABLE reach10_mysql.contract (
    id integer NOT NULL,
    c_id character varying(255),
    c_code character varying(255),
    c_name character varying(255),
    con_type character varying(255),
    package character varying(255),
    agr_upload character varying(255),
    monthlyc_desc character varying(255),
    monthlyc_amt character varying(255),
    act_date date,
    con_period character varying(255),
    status character varying(255),
    remarks character varying(255),
    remarks2 character varying(255)
);


ALTER TABLE reach10_mysql.contract OWNER TO postgres;

--
-- TOC entry 285 (class 1259 OID 17995)
-- Name: contract_id_seq; Type: SEQUENCE; Schema: reach10_mysql; Owner: postgres
--

ALTER TABLE reach10_mysql.contract ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME reach10_mysql.contract_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 286 (class 1259 OID 17996)
-- Name: customer_phoneline; Type: TABLE; Schema: reach10_mysql; Owner: postgres
--

CREATE TABLE reach10_mysql.customer_phoneline (
    cpl_id integer NOT NULL,
    cpl_debtorcode character varying(255) NOT NULL,
    cpl_phoneno character varying(25) NOT NULL,
    cpl_status character varying(255) NOT NULL,
    cpl_debtorid character varying(255) NOT NULL,
    cpl_extensionline character varying(255) NOT NULL,
    cpl_databasetype character varying(255) NOT NULL,
    planid character varying(255),
    cpl_rental character varying(255),
    cpl_rentaldate date
);


ALTER TABLE reach10_mysql.customer_phoneline OWNER TO postgres;

--
-- TOC entry 287 (class 1259 OID 18008)
-- Name: customer_phoneline_cpl_id_seq; Type: SEQUENCE; Schema: reach10_mysql; Owner: postgres
--

ALTER TABLE reach10_mysql.customer_phoneline ALTER COLUMN cpl_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME reach10_mysql.customer_phoneline_cpl_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 288 (class 1259 OID 18009)
-- Name: customer_phoneline_detail; Type: TABLE; Schema: reach10_mysql; Owner: postgres
--

CREATE TABLE reach10_mysql.customer_phoneline_detail (
    id integer NOT NULL,
    debtorid character varying(255) NOT NULL,
    debtorname character varying(255) NOT NULL,
    debtorcode character varying(255) NOT NULL,
    siteid character varying(255) NOT NULL,
    planid character varying(255) NOT NULL,
    status character varying(255) NOT NULL,
    package_name character varying(2000),
    port_no character varying(255)
);


ALTER TABLE reach10_mysql.customer_phoneline_detail OWNER TO postgres;

--
-- TOC entry 289 (class 1259 OID 18021)
-- Name: customer_phoneline_detail_id_seq; Type: SEQUENCE; Schema: reach10_mysql; Owner: postgres
--

ALTER TABLE reach10_mysql.customer_phoneline_detail ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME reach10_mysql.customer_phoneline_detail_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 290 (class 1259 OID 18022)
-- Name: deposit; Type: TABLE; Schema: reach10_mysql; Owner: postgres
--

CREATE TABLE reach10_mysql.deposit (
    id integer NOT NULL,
    c_id character varying(255),
    c_code character varying(255),
    c_name character varying(255),
    deposit_amt character varying(255),
    receipt_no character varying(255),
    paid_date date,
    status character varying(255),
    remarks character varying(255),
    remarks2 character varying(255)
);


ALTER TABLE reach10_mysql.deposit OWNER TO postgres;

--
-- TOC entry 291 (class 1259 OID 18028)
-- Name: e_invoice; Type: TABLE; Schema: reach10_mysql; Owner: postgres
--

CREATE TABLE reach10_mysql.e_invoice (
    id integer NOT NULL,
    invoice_no character varying(255) NOT NULL,
    uuid character varying(255) NOT NULL,
    remark text,
    status character varying(20),
    long_id text,
    submit_datetime timestamp without time zone NOT NULL,
    is_valid_datetime timestamp without time zone,
    cancel_datetime timestamp without time zone,
    cancel_reason character varying(255)
);


ALTER TABLE reach10_mysql.e_invoice OWNER TO postgres;

--
-- TOC entry 292 (class 1259 OID 18037)
-- Name: e_invoice_id_seq; Type: SEQUENCE; Schema: reach10_mysql; Owner: postgres
--

ALTER TABLE reach10_mysql.e_invoice ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME reach10_mysql.e_invoice_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 293 (class 1259 OID 18038)
-- Name: idd_rates; Type: TABLE; Schema: reach10_mysql; Owner: postgres
--

CREATE TABLE reach10_mysql.idd_rates (
    idd_id integer NOT NULL,
    idd_code character varying(255),
    idd_destination character varying(255),
    idd_sec integer,
    idd_rate double precision,
    call_id integer,
    idd_status character varying(255),
    pack_id integer
);


ALTER TABLE reach10_mysql.idd_rates OWNER TO postgres;

--
-- TOC entry 294 (class 1259 OID 18044)
-- Name: idd_rates_idd_id_seq; Type: SEQUENCE; Schema: reach10_mysql; Owner: postgres
--

ALTER TABLE reach10_mysql.idd_rates ALTER COLUMN idd_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME reach10_mysql.idd_rates_idd_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 295 (class 1259 OID 18045)
-- Name: inv_searchrecord; Type: TABLE; Schema: reach10_mysql; Owner: postgres
--

CREATE TABLE reach10_mysql.inv_searchrecord (
    id integer NOT NULL,
    invoice_code character varying(255),
    search_start character varying(255),
    search_end character varying(255),
    debtor_name character varying(255),
    debtor_id character varying(255),
    bill_start character varying(255),
    bill_end character varying(255),
    po_no character varying(50)
);


ALTER TABLE reach10_mysql.inv_searchrecord OWNER TO postgres;

--
-- TOC entry 296 (class 1259 OID 18051)
-- Name: inv_searchrecord_id_seq; Type: SEQUENCE; Schema: reach10_mysql; Owner: postgres
--

ALTER TABLE reach10_mysql.inv_searchrecord ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME reach10_mysql.inv_searchrecord_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 297 (class 1259 OID 18052)
-- Name: site_detail; Type: TABLE; Schema: reach10_mysql; Owner: postgres
--

CREATE TABLE reach10_mysql.site_detail (
    id integer NOT NULL,
    site_id integer,
    debtorid character varying(255),
    customer_name character varying(255),
    customer_code character varying(255),
    status character varying(255)
);


ALTER TABLE reach10_mysql.site_detail OWNER TO postgres;

--
-- TOC entry 298 (class 1259 OID 18058)
-- Name: site_detail_id_seq; Type: SEQUENCE; Schema: reach10_mysql; Owner: postgres
--

ALTER TABLE reach10_mysql.site_detail ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME reach10_mysql.site_detail_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 299 (class 1259 OID 18059)
-- Name: site_setting; Type: TABLE; Schema: reach10_mysql; Owner: postgres
--

CREATE TABLE reach10_mysql.site_setting (
    id integer NOT NULL,
    site_code character varying(255),
    site_name character varying(255),
    bill_code character varying(255),
    system_type character varying(255),
    url_path character varying(255),
    database_name character varying(255),
    port character varying(255),
    site_status character varying(255),
    running_number integer,
    digit_number integer,
    bill_due_date character varying(255)
);


ALTER TABLE reach10_mysql.site_setting OWNER TO postgres;

--
-- TOC entry 300 (class 1259 OID 18065)
-- Name: site_setting_id_seq; Type: SEQUENCE; Schema: reach10_mysql; Owner: postgres
--

ALTER TABLE reach10_mysql.site_setting ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME reach10_mysql.site_setting_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 301 (class 1259 OID 18066)
-- Name: std_rates; Type: TABLE; Schema: reach10_mysql; Owner: postgres
--

CREATE TABLE reach10_mysql.std_rates (
    std_id integer NOT NULL,
    std_code character varying(255),
    std_destination character varying(255),
    std_sec character varying(255),
    std_sec_rate character varying(255),
    std_sec_2 character varying(255),
    std_sec_rate_2 character varying(255),
    pack_id integer,
    line_id integer,
    std_status character varying(255),
    std_checkstatus character varying(255)
);


ALTER TABLE reach10_mysql.std_rates OWNER TO postgres;

--
-- TOC entry 302 (class 1259 OID 18072)
-- Name: std_rates_std_id_seq; Type: SEQUENCE; Schema: reach10_mysql; Owner: postgres
--

ALTER TABLE reach10_mysql.std_rates ALTER COLUMN std_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME reach10_mysql.std_rates_std_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 5036 (class 2606 OID 18074)
-- Name: contract contract_pkey; Type: CONSTRAINT; Schema: reach10_mysql; Owner: postgres
--

ALTER TABLE ONLY reach10_mysql.contract
    ADD CONSTRAINT contract_pkey PRIMARY KEY (id);


--
-- TOC entry 5040 (class 2606 OID 18076)
-- Name: customer_phoneline_detail customer_phoneline_detail_pkey; Type: CONSTRAINT; Schema: reach10_mysql; Owner: postgres
--

ALTER TABLE ONLY reach10_mysql.customer_phoneline_detail
    ADD CONSTRAINT customer_phoneline_detail_pkey PRIMARY KEY (id);


--
-- TOC entry 5038 (class 2606 OID 18078)
-- Name: customer_phoneline customer_phoneline_pkey; Type: CONSTRAINT; Schema: reach10_mysql; Owner: postgres
--

ALTER TABLE ONLY reach10_mysql.customer_phoneline
    ADD CONSTRAINT customer_phoneline_pkey PRIMARY KEY (cpl_id);


--
-- TOC entry 5042 (class 2606 OID 18080)
-- Name: deposit deposit_pkey; Type: CONSTRAINT; Schema: reach10_mysql; Owner: postgres
--

ALTER TABLE ONLY reach10_mysql.deposit
    ADD CONSTRAINT deposit_pkey PRIMARY KEY (id);


--
-- TOC entry 5044 (class 2606 OID 18082)
-- Name: e_invoice e_invoice_pkey; Type: CONSTRAINT; Schema: reach10_mysql; Owner: postgres
--

ALTER TABLE ONLY reach10_mysql.e_invoice
    ADD CONSTRAINT e_invoice_pkey PRIMARY KEY (id);


--
-- TOC entry 5046 (class 2606 OID 18084)
-- Name: idd_rates idd_rates_pkey; Type: CONSTRAINT; Schema: reach10_mysql; Owner: postgres
--

ALTER TABLE ONLY reach10_mysql.idd_rates
    ADD CONSTRAINT idd_rates_pkey PRIMARY KEY (idd_id);


--
-- TOC entry 5048 (class 2606 OID 18086)
-- Name: inv_searchrecord inv_searchrecord_pkey; Type: CONSTRAINT; Schema: reach10_mysql; Owner: postgres
--

ALTER TABLE ONLY reach10_mysql.inv_searchrecord
    ADD CONSTRAINT inv_searchrecord_pkey PRIMARY KEY (id);


--
-- TOC entry 5050 (class 2606 OID 18088)
-- Name: site_detail site_detail_pkey; Type: CONSTRAINT; Schema: reach10_mysql; Owner: postgres
--

ALTER TABLE ONLY reach10_mysql.site_detail
    ADD CONSTRAINT site_detail_pkey PRIMARY KEY (id);


--
-- TOC entry 5052 (class 2606 OID 18090)
-- Name: site_setting site_setting_pkey; Type: CONSTRAINT; Schema: reach10_mysql; Owner: postgres
--

ALTER TABLE ONLY reach10_mysql.site_setting
    ADD CONSTRAINT site_setting_pkey PRIMARY KEY (id);


--
-- TOC entry 5054 (class 2606 OID 18092)
-- Name: std_rates std_rates_pkey; Type: CONSTRAINT; Schema: reach10_mysql; Owner: postgres
--

ALTER TABLE ONLY reach10_mysql.std_rates
    ADD CONSTRAINT std_rates_pkey PRIMARY KEY (std_id);


-- Completed on 2026-03-10 11:47:43

--
-- PostgreSQL database dump complete
--

\unrestrict rDAbeUtflX5w1Pbim9eXy0xYjbJ28oLzKvAbjbYn4VR9f8eXprPb45xwcfW1mNj

